### ISSUE TITLE
Page creations not tracked by bot

### ISSUE THREAD

**Issue by L235** [L235/hat-collector#1]
`22:55 <PhantomTech> The log format for a new page is different than other logs, line 49 doesn't match the new page log
22:56 <PhantomTech> [[Special:Log/delete]] delete  * PhantomTech *  deleted "[[User:PhantomTech/sandbox]]": Author's request
22:56 <PhantomTech> [[User:PhantomTech/sandbox]] N https://test.wikipedia.org/w/index.php?oldid=516074&rcid=622295 * PhantomTech * (+4) Created page with "test"
23:04 <PhantomTech> L235: Don't know about becoming a maintainer but here's new regex that may fix the issue or may break everything
23:04 <PhantomTech>  \[\[(.+)\]\] (?P<log>.+) (?P<url>\S+)? \* (?P<user>.+) \* (?:\((?P<diff_size>\S+)\))? (?P<summary>.+)
23:04 <PhantomTech> a rule update/addition might be required after updating the regex
23:06 <+L235> can I put this chat log in a public issue?
23:06 <PhantomTech> yes
23:06 <+L235> otherwise I'm not gonna be able to find it again haha
23:07 <PhantomTech> theres an extra space at the start of the regex because I was worried my irc client would get upset with me but the regex should start with \ and end with )
`

**Comment by PhantomTech** [comment]
### Previous update
> Minor update, there is a second regex on line 51 (which lets be honest, is so far from line 49 it was unreasonable to think I'd see it) which matches "diffs", which includes new pages and already matches the new page log. Replacing that other regex with mine will more likely break something than not, development oopsie
### Current update
I'm not able to reproduce the behavior. I haven't been able to fully run the bot for debugging but I couldn't find any issues in the parts I was able to run. #2 might be able to give more info to debug a rule based issue but I don't think it's related to rules.

**Comment by L235** [comment]
Thanks for looking into this, @PhantomTech. This is very helpful.
