### ISSUE TITLE
Bot doesn't detect wikidata events

### ISSUE THREAD

**Issue by PhantomTech** [L235/hat-collector#12]
**Describe the bug**
See title

**To reproduce**
Add rule for wikidata
Trigger event on wikidata
Watch as event is not relayed by bot

**Expected behavior**
Event gets relayed by bot

**Console output**
Unavailable

**Environment:**
- Wikimedia Cloud Services
 - OS: Unknown, not needed
 - Python Version: Unknown, not needed
 - hat-collector Version/Commit: Probably e099f990fa8974c27dc025b297c4a0f7f509a2cf

**Comment by L235** [comment]
Switched to this branch.

**Comment by L235** [comment]
I believe the wiki formerly at that address is now at https://foundation.wikimedia.org/wiki/Home. Anyway, I guess nobody cares about that wiki enough to watch it? :)
