### ISSUE TITLE
URL Shortening

### ISSUE THREAD

**Issue by PhantomTech** [L235/hat-collector#8]
Using w.wiki URL shortened links was suggested by a user on IRC. Below are additional details and potential issues.

- URL shortener may not be indented for uses like this where a high rate and volume of shortens is likely.
- At a minimum caching should be done to prevent more than one API request when forwarding the same diff to multiple channels.
- Documentation at meta indicates a rate limit of 10 or 50 shortens per 2 minutes depending on if logged in or not which may be extremely restrictive, even if logging in is implemented.
- A possible mitigation to the rate limit issue is a per channel option that can only be togged by users with a sufficient authorization level.
- API info is at https://meta.wikimedia.org/w/api.php?action=help&modules=shortenurl
- Documentation is at https://meta.wikimedia.org/wiki/Wikimedia_URL_Shortener and https://www.mediawiki.org/wiki/Extension:UrlShortener

My personal opinion is that implementing this may be a potential abuse of the service and would not be significantly beneficial to the bot but would be severely restricted by rate limits. The only benefit that I can see is that edit summaries would need to be shortened less often for the full message to fit in one message. Conditionally shortening URLs only when the edit summary would be saved from shortening may have some benefit, but the bot could also be made to try splitting off the URL into a separate message in those instances instead.

**Comment by L235** [comment]
Yeah, I think I agree with your last paragraph. I'm not sure I really see the point to doing this. I think a viable alternative would be allowing the "cut off edit summary" behavior to be set on a channel-by-channel or even rule-by-rule basis. Shortening, using the official w.wiki shortener, for links that (in a lot of cases) will not be clicked even once and absolutely will never need to be entered by hand (which is the classic case for shortening) just isn't worth it IMO.
